[tools]
bat = "0.26.1"
carapace-bin = "1.6.2"
delta = "0.18.2"
eza = "0.23.4"
ffmpeg = "8.0.1"
fzf = "0.67.0"
jq = "1.8.1"
neovim = "0.11.6"
ripgrep = "15.1.0"
starship = "1.24.2"
vivid = "0.10.1"
zoxide = "0.9.9"

[alias]
carapace-bin = "asdf:vic1707/asdf-carapace-bin"

[settings]
idiomatic_version_file_enable_tools = []

## Not working on Mac Apple Silicon ##
# imagemagick = "7.1.2-13"
